import './globals.css'
import Providers from './providers.js'

export const metadata = {
  title: 'Tyler Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
